### ISSUE TITLE
Latest canary breaks plugin initialization

### ISSUE THREAD

**Issue by GH0STP4WZ** [plooshi/BDExperiments#2]
The latest canary update breaks initialization. Throwing the following error. ![Image](https://i.imgur.com/WIRJ0OC.png)

**Comment by plooshi** [comment]
Alright, a comment on the gist has a working version, so i will update it.

**Comment by GH0STP4WZ** [comment]
Works 👍

**Comment by plooshi** [comment]
@Bass-PHOX np!
